module.exports = {
  Types,
  connect,
  close,
  addConnection,
  getConnection,
  addDatabase,
  getDatabase,
  addModels,
  addModel,
  removeModel,
  removeModels,
  addGlobalErrorHandler,
  setDefaultDb,
} = require('./api');
